import styles from '@/styles/Home.module.css'
import { Capacitor } from '@capacitor/core'
import { IonContent, IonHeader, IonTitle, IonToolbar } from '@ionic/react'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const isPlatform = Capacitor.isNativePlatform()
	console.log('isPlatform 123', isPlatform)
	return (
		<>
			<Head>
				<title>Create Mobile app</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1, viewport-fit=cover'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<IonHeader>
				<IonToolbar color='primary'>
					<IonTitle>Header12312</IonTitle>
				</IonToolbar>
			</IonHeader>
			<IonContent className='ion-padding'>
				<h1>Content </h1>
			</IonContent>

			<main className={`${styles.main} ${inter.className}`}>
				<h1>Hi my mobile </h1>
			</main>
		</>
	)
}
